{% set name = "lsds" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/funkelab/lsd/archive/v{{ version }}.tar.gz
  sha256: 55c01da59e468a537ca516733ff5eb6b5e978bcee2718eede2e735f486bd1ec1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py
    - scikit-image
    - requests
    - cython
    - gunpowder
test:
  imports:
    - lsd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funkey/lsd
  license: MIT
  license_file: LICENSE
  summary: A package for computing local shape descriptors of segmantation arrays

extra:
  recipe-maintainers:
    - pattonw
    - sheridana
